"""increase_num_char_from_rule

Revision ID: 08e502f16004
Revises: 317b24b722f0
Create Date: 2026-09-21 05:09:24.473643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08e502f16004'
down_revision: Union[str, Sequence[str], None] = '317b24b722f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'name',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###
