"""add_index

Revision ID: 0c83f1ef658c
Revises: c255664286d3
Create Date: 2026-09-03 06:41:55.255146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c83f1ef658c'
down_revision: Union[str, Sequence[str], None] = 'c255664286d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ticket_user', 'tickets', ['user_id'], unique=False)
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name', table_name='users')
    op.alter_column('users', 'name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('idx_ticket_user', table_name='tickets')
    # ### end Alembic commands ###
