"""add_user_credentials

Revision ID: 2eaf348f498e
Revises: d68da8c64747
Create Date: 2026-09-09 13:55:30.459274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2eaf348f498e'
down_revision: Union[str, Sequence[str], None] = 'd68da8c64747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('hash_password', sa.String(), nullable=True))
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['hash_password'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'tg_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'hash_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
