"""fix_user_credentials

Revision ID: 3a06dd970ee0
Revises: 2eaf348f498e
Create Date: 2026-09-09 14:17:06.551738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a06dd970ee0'
down_revision: Union[str, Sequence[str], None] = '2eaf348f498e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.drop_constraint(op.f('users_hash_password_key'), 'users', type_='unique')
    op.create_check_constraint('not null tg and email from user', 'users', 'NOT (tg_id IS NULL AND email IS NULL)')
    op.drop_column('users', 'hash_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('not null tg and email from user', 'users', type_='check')
    op.create_unique_constraint(op.f('users_hash_password_key'), 'users', ['hash_password'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
