"""add_subcribe_for_role

Revision ID: 3fd3016d972a
Revises: a496f6fa4e08
Create Date: 2026-09-10 21:54:23.002959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3fd3016d972a'
down_revision: Union[str, Sequence[str], None] = 'a496f6fa4e08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE classrule ADD VALUE 'ALL'")
    class_rule_enum = postgresql.ENUM(
        'CRITICAL_ALERTS',
        'SECURITY_ALERTS',
        'HR_ALERTS',
        'CASH_ALERTS',
        'SERVICE_ALERTS',
        'BAR_EQUIPMENT',
        'REFRIGERATION',
        'ELECTRICAL',
        'PLUMBING',
        'FURNITURE',
        'CLIMATE',
        'CONSUMABLE_EQUIPMENT',
        'STORE_REQUEST',
        'INVENTORY_REQUEST',
        'MARKETING_REQUEST',
        'SECURITY_REQUEST',
        'IT_REQUEST',
        'ALL',
        name='classrule',
        create_type=False,
    )
    op.create_table('role_subscribers',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('class_rule', class_rule_enum, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'class_rule')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_subscribers')
    # ### end Alembic commands ###
