"""add_email

Revision ID: 5697ac5ceac1
Revises: 0c83f1ef658c
Create Date: 2026-09-03 07:55:32.838278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5697ac5ceac1'
down_revision: Union[str, Sequence[str], None] = '0c83f1ef658c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def add_email(con: sa.Connection):
    users = sa.table(
        "users",
        sa.column("name"),
        sa.column("email")
    )
    stmd = sa.update(users).values(
            email=sa.func.lower(
                sa.column("name")
            ) + "@example.com")
    con.execute(stmd)

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    connect = op.get_bind()
    add_email(connect)

    op.alter_column(
        "users",
        "email",
        nullable=False
    )
    op.create_unique_constraint(
        "uq_users_email",
        "users",
        ["email"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
