"""add_resposibility_from_role

Revision ID: a496f6fa4e08
Revises: 3a06dd970ee0
Create Date: 2026-09-10 10:32:01.695543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a496f6fa4e08'
down_revision: Union[str, Sequence[str], None] = '3a06dd970ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_responsibility',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('class_rule', sa.Enum('CRITICAL_ALERTS', 'SECURITY_ALERTS', 'HR_ALERTS', 'CASH_ALERTS', 'SERVICE_ALERTS', 'BAR_EQUIPMENT', 'REFRIGERATION', 'ELECTRICAL', 'PLUMBING', 'FURNITURE', 'CLIMATE', 'CONSUMABLE_EQUIPMENT', 'STORE_REQUEST', 'INVENTORY_REQUEST', 'MARKETING_REQUEST', 'SECURITY_REQUEST', 'IT_REQUEST', name='classrule'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'class_rule')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_responsibility')
    # ### end Alembic commands ###
