"""ticket_users_fk

Revision ID: c255664286d3
Revises: c97aa9130b71
Create Date: 2026-09-02 05:56:58.013985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c255664286d3'
down_revision: Union[str, Sequence[str], None] = 'c97aa9130b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tickets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'user_id')
    # ### end Alembic commands ###
