"""add_role_flags

Revision ID: d68da8c64747
Revises: 7d5531cb47eb
Create Date: 2026-09-09 11:44:24.044288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68da8c64747'
down_revision: Union[str, Sequence[str], None] = '7d5531cb47eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('need_branch', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('need_department', sa.Boolean(), nullable=False))
    op.create_check_constraint('not_depart_and_branch_on_role', 'roles', 'NOT (need_branch AND need_department)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('not_depart_and_branch_on_role', 'roles', type_='check')
    op.drop_column('roles', 'need_department')
    op.drop_column('roles', 'need_branch')
    # ### end Alembic commands ###
