"""fix_role

Revision ID: db134a951dc8
Revises: 3a06dd970ee0
Create Date: 2026-09-15 03:00:54.890360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db134a951dc8'
down_revision: Union[str, Sequence[str], None] = '3a06dd970ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    class_rule_enum = postgresql.ENUM('CRITICAL_ALERTS',
                                      'SECURITY_ALERTS',
                                      'HR_ALERTS',
                                      'CASH_ALERTS',
                                      'SERVICE_ALERTS',
                                      'BAR_EQUIPMENT',
                                      'REFRIGERATION',
                                      'ELECTRICAL',
                                      'PLUMBING',
                                      'FURNITURE',
                                      'CLIMATE',
                                      'CONSUMABLE_EQUIPMENT',
                                      'STORE_REQUEST',
                                      'INVENTORY_REQUEST',
                                      'MARKETING_REQUEST',
                                      'SECURITY_REQUEST',
                                      'IT_REQUEST',
                                      'ALL', name='classrule',
                                      create_type=False)
    op.create_table('responsibilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('class_rule',class_rule_enum,nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'class_rule')
    )

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('class_rule',class_rule_enum, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'class_rule')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_table('responsibilities')
    # ### end Alembic commands ###
