from enum import Enum

class State(Enum):
    NEW = 'NEW'
    CONFIRMED = 'CONFIRMED'
    IN_PROGRESS = 'IN_PROGRESS'
    WAITING_EXTERNAL = 'WAITING_EXTERNAL'
    RESOLVED = 'RESOLVED'
    CLOSED = 'CLOSED'
    CANCELLED = 'CANCELLED'


class KindRule(Enum):
    OBJECT = 'OBJECT'
    REQUEST = 'REQUEST'
    ALERT = 'ALERT'

class ClassRule(Enum):
    CRITICAL_ALERTS = 'CRITICAL_ALERTS'
    SECURITY_ALERTS = 'SECURITY_ALERTS'
    HR_ALERTS = 'HR_ALERTS'
    CASH_ALERTS = 'CASH_ALERTS'
    SERVICE_ALERTS = 'SERVICE_ALERTS'
    BAR_EQUIPMENT = 'BAR_EQUIPMENT'
    REFRIGERATION = 'REFRIGERATION'
    ELECTRICAL = 'ELECTRICAL'
    PLUMBING = 'PLUMBING'
    FURNITURE = 'FURNITURE'
    CLIMATE = 'CLIMATE'
    CONSUMABLE_EQUIPMENT = 'CONSUMABLE_EQUIPMENT'
    STORE_REQUEST = 'STORE_REQUEST'
    INVENTORY_REQUEST = 'INVENTORY_REQUEST'
    MARKETING_REQUEST = 'MARKETING_REQUEST'
    SECURITY_REQUEST = 'SECURITY_REQUEST'
    IT_REQUEST = 'IT_REQUEST'

class Severity(Enum):
    FULL_FAILURE = 'FULL_FAILURE'
    PARTIAL_PROBLEM = 'PARTIAL_PROBLEM'
    MINOR_ISSUE = 'MINOR_ISSUE'
    INCIDENT = 'INCIDENT'
    REQUEST = 'REQUEST'



DATE_FORMAT = "%Y-%m-%d %H:%M:%S"